name: wemake

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: wemake-python-styleguide
    uses: wemake-services/wemake-python-styleguide@0.16.1
    continue-on-error: true
    with:
      reporter: 'github-pr-check'
    env:
      GITHUB_TOKEN: ${{ secrets.LINT_TOKEN }}
