name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.16.1
        continue-on-error: true
        with:
          reporter: 'github-pr-check'
        env:
          GITHUB_TOKEN: ${{ secrets.LINT_TOKEN }}
